force-app/main/default/objects/Object_Visualizer__mdt/Object_Visualizer__mdt.object-meta.xml
<CustomObject>
    <description>Allows for object drill down.</description>
    <label>Object Visualizer</label>
    <pluralLabel>Ojbect Visualizers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Object_Visualizer__mdt/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <label>DeveloperName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Visualizer__mdt/fields/Last_Date_Updated__c.field-meta.xml
<CustomField>
    <fullName>Last_Date_Updated__c</fullName>
    <description>Last date the associated objects were created</description>
    <label>Last Date Updated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Object_Visualizer__mdt/fields/Object_Related_Objects__c.field-meta.xml
<CustomField>
    <fullName>Object_Related_Objects__c</fullName>
    <label>Object Related Objects</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/createMetadata.cls
public class createMetadata implements Metadata.DeployCallback{
    public void handleResult(Metadata.DeployResult result, Metadata.DeployCallbackContext context) {
        if (result.status == Metadata.DeployStatus.Succeeded) { // i should really just have somekind of return. don't konw how tho... this worked
            System.debug(' success : '+ result);
        } else {
            System.debug(' fail : '+ result);
        }
    }

    public static Id updateAccVisualizerLookups(String recordName, String lookups) {
        Object_Visualizer__mdt customMetadataRecord = [SELECT Id, MasterLabel FROM Object_Visualizer__mdt WHERE MasterLabel=:recordName LIMIT 1];
        Metadata.CustomMetadata customMetadata = new Metadata.CustomMetadata();
        customMetadata.fullName = 'Object_Visualizer.' + recordName;
        customMetadata.label = recordName;
        // i only need 1. so i think this is fine tbh
        Metadata.CustomMetadataValue customLookups = new Metadata.CustomMetadataValue();
        customLookups.field = 'Object_Related_Objects__c';
        customLookups.value = lookups;
        customMetadata.values.add(customLookups);

        Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
        mdContainer.addMetadata(customMetadata);
        createMetadata callback = new createMetadata();
        Id jobId = Metadata.Operations.enqueueDeployment(mdContainer, callback);

        return jobId;
    }

    public static Id createAccVisualizerMetadata(String label, String lookups, String devName) { 
        DateTime nowDateTime = DateTime.now();
        Date nowDate = nowDateTime.date();

        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
        customMetadata.fullName = 'Object_Visualizer.' + label; //'Object_Visualizer.Admin';
        customMetadata.label = label; //'Admin';

        // there's a way to automate this, but i only have these 2 so. good for now
        Metadata.CustomMetadataValue customLookups = new Metadata.CustomMetadataValue();
        customLookups.field = 'Object_Related_Objects__c';
        customLookups.value = lookups;//'test';
        customMetadata.values.add(customLookups);
        Metadata.CustomMetadataValue customLastDate = new Metadata.CustomMetadataValue();
        customLastDate.field = 'Last_Date_Updated__c';
        customLastDate.value = nowDate;
        customMetadata.values.add(customLastDate);
        Metadata.CustomMetadataValue customDeveloperName = new Metadata.CustomMetadataValue();
        customDeveloperName.field = 'DeveloperName__c'; 
        customDeveloperName.value = devName; // devName
        customMetadata.values.add(customDeveloperName);

        Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
        mdContainer.addMetadata(customMetadata);
        createMetadata callback = new createMetadata();
        Id jobId = Metadata.Operations.enqueueDeployment(mdContainer, callback);
        
        return jobId; // gonna query for this one on the other side
    }
}